[env:debug]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyACM*
monitor_port = /dev/ttyACM*
lib_deps =
    fastled/FastLED
build_flags =
    -I include
    -D DEBUG_ENABLED
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
build_src_filter =
    +<main.cpp>

[env:release]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyACM*
monitor_port = /dev/ttyACM*
lib_deps =
    fastled/FastLED
build_flags =
    -I include
    -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter =
    +<main.cpp>

[env:test_lights]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
build_flags =
    -I include
    -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter =
    +<main_test_lights.cpp>
