; One PlatformIO project for 3 ESP32 nodes (same hardware profile)

[env]
platform = espressif32
board = upesy_wroom
framework = arduino
monitor_speed = 115200
build_src_filter = +<main.cpp>

[env:esp1]
build_flags =
  -DTWAI_TX_GPIO=4
  -DTWAI_RX_GPIO=5
  -DNODE_ROLE=1
  -DNODE_ID=1

[env:esp2]
build_flags =
  -DTWAI_TX_GPIO=4
  -DTWAI_RX_GPIO=5
  -DNODE_ROLE=2
  -DNODE_ID=2

[env:esp3]
build_flags =
  -DTWAI_TX_GPIO=4
  -DTWAI_RX_GPIO=5
  -DNODE_ROLE=2
  -DNODE_ID=3
